lang: fr
title: Yasmine EL HASSANI
description: Template pour la création d'un repo type CV
theme: bulma-clean-theme

url: https://yasmineelhassani.github.io/

force_theme: light
permalink: pretty
lang: fr
theme_color: '#ffb4b4'
fixed_navbar: top
show_logo: true

collections:
  products: 
    output: true
    layout: product
    image: https://via.placeholder.com/800x600
    show_sidebar: false

plugins:
  - jekyll-remote-include

